pipeline {
    agent {label 'id-info-slave'}
    stages {
        stage('testing'){
            steps {
                echo 'Would be running automated tests here'
            }
        }
        stage('deploy'){
            agent { label 'prodstage'}
            steps {
                dir('billing-zero-config-report'){
                    sh 'make stage'
                }
            }
        }
        stage('cleanup'){
            agent {label 'prodstage'}
            steps {
                dir('billing-zero-config-report'){
                    sh 'make clean'
                }
            }
        }
    }
}