version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HttpApiStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-osmyge6x01am"
s3_prefix = "HttpApiStack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolId=\"us-east-1_DqqyuHMmq\" Audience=\"b320limnji202vqiurloaekne\""
